name: match_madness
description: A Duolingo-style Match Madness vocabulary game for Android.
publish_to: 'none'
version: 1.0.2+4

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  file_picker: ^8.0.0
  http: ^1.2.0
  flutter_tts: ^3.8.5
  audioplayers: ^6.1.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/default_words.json